### PR TITLE
Fix conditional rendering of preferred skills

### PR DESCRIPTION
**Pull request by TheFehr**

### CODE REVIEW

**Review by lukasbischof — COMMENTED** [review]
What about required skills?

**Comment by TheFehr** [comment]
> 
> 
> What about required skills?

that is required, no?

**Comment by lukasbischof** [comment]
ah yeah

**Comment by TheFehr** [comment]
> 
> 
> ah yeah. Maybe it should still be optional, idk

Made both optional. Scraper sends both anyways. But this way claimed ones can choose to leave them empty

**Review by lukasbischof — APPROVED** [review]

**Pull request merged**
